routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WebController@welcome');

// Registration Routes
Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/register', 'Auth\RegisterController@register')->name('auth.register');

// Authentication Routes
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login')->name('auth.login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

Route::group([
    'as' => 'web.'
], function () {
    
    Route::group(['as' => 'product.'], function() {
        Route::get('/shop/products', 'WebController@indexProduct')->name('index');
        Route::get('{taxon}/c', 'WebController@indexProduct')->name('category');
        Route::get('{product}/p', 'WebController@showProduct')->name('show');
    });

    Route::group(['prefix' => 'cart', 'as' => 'cart.'], function() {
        Route::get('show', 'CartController@show')->name('show');
        Route::post('add/{product}', 'CartController@add')->name('add');
        Route::post('update/{cart_item}', 'CartController@update')->name('update');
        Route::post('remove/{cart_item}', 'CartController@remove')->name('remove');
    });
});

Route::group([
    'prefix' => 'admin',
    'middleware' => 'auth:admin'
], function () {

    //Route::redirect('/', '/dashboard', 301);
    Route::view('/dashboard', 'admin.dashboard');
    
    /* Route Roles  */
    Route::resource('role', 'RoleController')->except(['show', 'destroy']);
    Route::delete('role/delete', 'RoleController@delete')->name('role.delete');

    /* Route Users  */
    Route::resource('user', 'UserController')->except(['show', 'destroy']);
    Route::delete('user/delete', 'UserController@delete')->name('user.delete');

    /* Route Customers  */
    Route::resource('customer', 'CustomerController')->except(['destroy']);
    Route::delete('customer/delete', 'CustomerController@delete')->name('customer.delete');
    
    /* Route Address  */
    Route::resource('address', 'AddressController')->only(['create', 'store']);
    Route::delete('address/delete', 'AddressController@delete')->name('address.delete');

    /* Route Taxonomies  */
    Route::resource('taxonomy', 'TaxonomyController')->except(['destroy']);
    Route::delete('taxonomy/delete', 'TaxonomyController@delete')->name('taxonomy.delete');

    /* Route Taxons  */
    Route::group(['prefix' => 'taxonomy/{taxonomy}'], function () {
        Route::resource('taxon', 'TaxonController')->except(['index', 'show', 'destroy']);
        Route::delete('taxon/delete', 'TaxonController@delete')->name('taxon.delete');
    });

    /* Route Products  */
    Route::resource('product', 'ProductController')->except(['destroy']);
    Route::delete('product/delete', 'ProductController@delete')->name('product.delete');
    
});

resources/views/cart.blade.php
@extends('layouts.web')

@section('title')
    {{ __('Show cart') }}
@stop

@section('content')
    
    <!--shopping cart area start -->
    <div class="shopping_cart_area mt-32">
        <div class="container">  
            <div class="row">
                <div class="col-12">
                    <div class="table_desc">
                        <div class="cart_page table-responsive">
                            <table>
                                <thead>
                                    <tr>
                                        <th class="product_remove">Delete</th>
                                        <th class="product_thumb">Image</th>
                                        <th class="product_name">Product</th>
                                        <th class="product-price">Price</th>
                                        <th class="product_quantity">Quantity</th>
                                        <th class="product_total">Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse (Cart::getItems() as $item)
                                        <tr>
                                            <td class="product_remove">
                                                <form action="{{ route('web.cart.remove', $item) }}"
                                                    style="display: inline-block" method="POST">
                                                    @csrf
                                                    <button dusk="cart-delete-{{ $item->getProduct()->id }}" class="btn btn-link btn-sm"><i class="fa fa-trash-o"></i></button>
                                                </form>
                                            </td>
                                            <td class="product_thumb"><a href="#"><img src="{{$item->getThumbnailUrl()}}" alt=""></a></td>
                                            <td class="product_name"><a href="#">{{$item->name}}</a></td>
                                            <td class="product-price"> ${{$item->price}}</td>
                                            <td class="product_quantity">
                                                <label>Quantity</label> 
                                                <form id="update-item-{{ $item->getProduct()->id }}" action="{{ route('web.cart.update', $item) }}" 
                                                    style="display: inline-block" method="POST">
                                                    @csrf
                                                    <input data-id="{{ $item->getProduct()->id }}" name="qty" value="{{ $item->quantity }}" type="number" min="0" max="100" />
                                                </form>
                                            </td>
                                            <td class="product_total"> ${{$item->getTotalFormat()}}</td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="6">
                                                <div class="cart_empty">
                                                    {{__('Cart Empty')}}
                                                </div>
                                            </td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>   
                        </div>    
                    </div>
                 </div>
             </div>
             <!--coupon code area start-->
            <div class="coupon_area">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <!--
                        <div class="coupon_code left">
                                <h3>Coupon</h3>
                                <div class="coupon_inner">   
                                    <p>Enter your coupon code if you have one.</p>                                
                                    <input placeholder="Coupon code" type="text">
                                    <button type="submit">Apply coupon</button>
                                </div>    
                        </div>
                        -->
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="coupon_code right">
                            <h3>Cart Totals</h3>
                            <div class="coupon_inner">
                                <div class="cart_subtotal">
                                    <p>Subtotal</p>
                                    <p class="cart_amount"> ${{Cart::getSubtotal()}}</p>
                                </div>
                                <!--
                                <div class="cart_subtotal ">
                                    <p>Shipping</p>
                                    <p class="cart_amount"><span>Flat Rate:</span>  $255.00</p>
                                </div>
                                <a href="#">Calculate shipping</a>
                                -->
                                <hr>
                                <div class="cart_subtotal">
                                    <p>Total</p>
                                    <p class="cart_amount"> ${{Cart::getTotal()}}</p>
                                </div>
                                <div class="checkout_btn">
                                    <a href="#">Proceed to Checkout</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--coupon code area end-->
        </div>     
    </div>
    <!--shopping cart area end -->

    @include('elements._call_action')
@endsection

@section('scripts')
    @parent

    <script>
        $(document).ready(function(){
            $('input[name=qty]').on('input', function() {
                let id = $(this).data('id')
                document.getElementById('update-item-'+id).submit();
            })
        })
    </script>
@stop

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-5">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Home</h1>
    </div>
</main>
@endsection

resources/views/products.blade.php
@extends('layouts.web')

@section('content')
    <!--shop  area start-->
    <div class="shop_area shop_reverse">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-12">
                   <!--sidebar widget start-->
                    <aside class="sidebar_widget">
                        <div class="widget_inner">
                            <!--
                            <div class="widget_list widget_filter">
                                <h2>Filter by price</h2>
                                <form action="{{url()->full()}}"> 
                                    <div id="slider-range"></div>   
                                    <button type="submit">Filter</button>
                                    <input type="text" name="amount" id="amount" />   

                                </form> 
                            </div>
                            -->
                            @foreach ($taxonomies as $taxonomy)
                                <div class="widget_list widget_categories">
                                    <h2>{{$taxonomy->name}}</h2>
                                    <ul>
                                        @foreach ($taxonomy->rootLevelTaxons() as $taxon)
                                            <li>
                                                <input type="checkbox">
                                                <a href="{{route('web.product.category', $taxon->slug)}}">
                                                    {{$taxon->name}} ({{$taxon->products->count()}})
                                                </a> 
                                                <span class="checkmark"></span>
                                            </li>    
                                        @endforeach
                                        
                                    </ul>
                                </div>  
                            @endforeach
                            
                        </div>
                        <div class="shop_sidebar_banner">
                            <a href="#"><img src="assets/img/bg/banner9.jpg" alt=""></a>
                        </div>
                    </aside>
                    <!--sidebar widget end-->
                </div>
                <div class="col-lg-9 col-md-12">
                    <!--shop wrapper start-->
                    <!--shop toolbar start
                    <div class="shop_banner">
                        <img src="assets/img/bg/banner8.jpg" alt="">
                    </div>
                    <div class="shop_title">
                        <h1>shop</h1>
                    </div>
                    <div class="shop_toolbar_wrapper">
                        <div class="shop_toolbar_btn">

                            <button data-role="grid_3" type="button" class="active btn-grid-3" data-toggle="tooltip" title="3"></button>

                            <button data-role="grid_4" type="button"  class=" btn-grid-4" data-toggle="tooltip" title="4"></button>

                            <button data-role="grid_list" type="button"  class="btn-list" data-toggle="tooltip" title="List"></button>
                        </div>
                        <div class=" niceselect_option">

                            <form class="select_option" action="#">
                                <select name="orderby" id="short">

                                    <option selected value="1">Sort by average rating</option>
                                    <option  value="2">Sort by popularity</option>
                                    <option value="3">Sort by newness</option>
                                    <option value="4">Sort by price: low to high</option>
                                    <option value="5">Sort by price: high to low</option>
                                    <option value="6">Product Name: Z</option>
                                </select>
                            </form>


                        </div>
                        <div class="page_amount">
                            <p>Showing 1–9 of 21 results</p>
                        </div>
                    </div>
                    shop toolbar end-->

                     <div class="row shop_wrapper">
                        @foreach ($products as $product)
                            <div class="col-lg-4 col-md-4 col-12 ">
                                <div class="single_product">
                                    <div class="product_name grid_name">
                                        <h3><a href="{{route('web.product.show', $product->slug)}}">{{$product->name}}</a></h3>
                                        <p class="manufacture_product"><a href="#">{{$product->taxons->first()->name}}</a></p>
                                    </div>
                                    <div class="product_thumb">
                                        <a class="primary_img" href="{{route('web.product.show', $product->slug)}}"><img src="{{$product->getThumbnailUrl()}}" alt=""></a>
                                        <!--
                                        <div class="label_product">
                                            <span class="label_sale">-47%</span>
                                        </div>
                                        <div class="action_links">
                                            <ul>
                                                <li class="quick_button"><a href="#" data-toggle="modal" data-target="#modal_box"  title="quick view"> <span class="lnr lnr-magnifier"></span></a></li>
                                                <li class="wishlist"><a href="wishlist.html" title="Add to Wishlist"><span class="lnr lnr-heart"></span></a></li>
                                                <li class="compare"><a href="#" title="compare"><span class="lnr lnr-sync"></span></a></li>
                                            </ul>
                                        </div>
                                    -->
                                    </div>
                                    <div class="product_content grid_content">
                                        <div class="content_inner">
                                            <div class="product_ratings">
                                                <ul>
                                                    <li><a href="#"><i class="ion-star"></i></a></li>
                                                    <li><a href="#"><i class="ion-star"></i></a></li>
                                                    <li><a href="#"><i class="ion-star"></i></a></li>
                                                    <li><a href="#"><i class="ion-star"></i></a></li>
                                                    <li><a href="#"><i class="ion-star"></i></a></li>
                                                </ul>
                                            </div>
                                            <div class="product_footer d-flex align-items-center">
                                                <div class="price_box">
                                                    <span class="current_price">${{$product->getPrice()}}</span>
                                                    <!--
                                                    <span class="old_price">$3200.00</span>   
                                                    -->
                                                </div>
                                                <div class="add_to_cart">
                                                    <a href="cart.html" title="add to cart"><span class="lnr lnr-cart"></span></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="product_content list_content">
                                        <div class="left_caption">
                                        <div class="product_name">
                                                <h3><a href="{{route('web.product.show', $product->slug)}}">Cas Meque Metus Shoes Core i7 3.4GHz, 16GB DDR3</a></h3>
                                            </div>
                                            <div class="product_ratings">
                                                <ul>
                                                    <li><a href="#"><i class="ion-star"></i></a></li>
                                                    <li><a href="#"><i class="ion-star"></i></a></li>
                                                    <li><a href="#"><i class="ion-star"></i></a></li>
                                                    <li><a href="#"><i class="ion-star"></i></a></li>
                                                    <li><a href="#"><i class="ion-star"></i></a></li>
                                                </ul>
                                            </div>
                                            
                                            <div class="product_desc">
                                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis ad, iure incidunt. Ab consequatur temporibus non eveniet inventore doloremque necessitatibus sed, ducimus quisquam, ad asperiores  </p>
                                            </div>
                                        </div>
                                        <div class="right_caption">
                                        <div class="text_available">
                                            <p>availabe: <span>99 in stock</span></p>
                                        </div>
                                        <div class="price_box">
                                                <span class="current_price">$160.00</span>
                                                <span class="old_price">$420.00</span>
                                            </div>
                                            <div class="cart_links_btn">
                                                <a href="#" title="add to cart">add to cart</a>
                                            </div>
                                            <div class="action_links_btn">
                                                <ul>
                                                    <li class="quick_button"><a href="#" data-toggle="modal" data-target="#modal_box"  title="quick view"> <span class="lnr lnr-magnifier"></span></a></li>
                                                    <li class="wishlist"><a href="wishlist.html" title="Add to Wishlist"><span class="lnr lnr-heart"></span></a></li>
                                                    <li class="compare"><a href="#" title="compare"><span class="lnr lnr-sync"></span></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>


                    {{ $products->links() }}
                    <!--shop toolbar end-->
                    <!--shop wrapper end-->
                </div>
            </div>
        </div>
    </div>
    <!--shop  area end-->
    
     <!--call to action start-->
    <section class="call_to_action">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="call_action_inner">
                        <div class="call_text">
                            <h3>We Have <span>Recommendations</span>  for You</h3>
                            <p>Take 30% off when you spend $150 or more with code Autima11</p>
                        </div>
                        <div class="discover_now">
                            <a href="#">discover now</a>
                        </div>
                        <div class="link_follow">
                            <ul>
                                <li><a href="#"><i class="ion-social-facebook"></i></a></li>
                                <li><a href="#"><i class="ion-social-twitter"></i></a></li>
                                <li><a href="#"><i class="ion-social-googleplus"></i></a></li>
                                <li><a href="#"><i class="ion-social-youtube"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--call to action end-->
@endsection